# Image
TAG := baseimage
USER := docker

BUILD_PARAMS := --build-arg FONTFORGE_URL="${FONTFORGE_URL}" --build-arg PDF2HTMLEX_URL="${PDF2HTMLEX_URL}" \
	--build-arg DUID="${DUID}" --build-arg DGID="${DGID}" --build-arg USER="${USER}"