image: docker:latest

services:
  - docker:dind

before_script:
  - apk --no-cache add make

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - make build
    - make save
  artifacts:
    paths:
      - image.tar

test:
  stage: test
  script:
    - echo "No testing at the moment"
  artifacts:
    paths:
      - image.tar

release:
  stage: release
  script:
    - docker load --input=image.tar
    - docker login -u $CI_BUILD_USER -p $CI_BUILD_TOKEN
    - make push