image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - apk --no-cache add make

stages:
  - build
  - test
  - release

variables:
  REGISTRY: registry.gitlab.com
  NAMESPACE: jrbeverly-docker
  PROJECT: docker-pdf2htmlex
  GIT_COMMIT: ${CI_COMMIT_SHA}
  PREFIX_TAG: ${CI_COMMIT_SHA}-
  RELEASE_IMAGE: docker.io/jrbeverly/pdf2htmlex
  IMAGE_VERSION: baseimage

# Build
#
# Build steps.
build:
  stage: build
  script:
    - make -C build/ $IMAGE_VERSION
    - make -C build/ TAG=$IMAGE_VERSION push
  only:
    - tags
    - /^versions-.*$/
  except:
    - master

# Test
#
# Test steps.
test:
  stage: test
  script:
    - make -s -C build/ TAG=$IMAGE_VERSION pull
    - make -s -C build/ TAG=$IMAGE_VERSION test
  dependencies:
    - build
  only:
    - tags
    - /^versions-.*$/
  except:
    - master

# Release
#
# Release steps.
release:
  stage: release
  script:
    - docker login -u $DOCKER_BUILD_USER -p $DOCKER_BUILD_TOKEN
    - make -C build/ TAG=$IMAGE_VERSION pull
    - make -C build/ TAG=$IMAGE_VERSION release
  dependencies:
    - test
  only:
    - tags
    - /^versions-.*$/
  except:
    - master